/**
 * Markdown formatter for the legitimacy report.
 *
 * Designed to be readable on a phone or laptop by multi-sig operators:
 * one-glance executive summary at the top, category-by-category breakdown
 * below, plus the failures and warnings consolidated for easy reference.
 */

import type {
  CategoryResult,
  CheckResult,
  LegitimacyReport
} from "../types";

const CATEGORY_TITLES: Record<"A" | "B" | "C" | "D" | "E" | "F", string> = {
  A: "Category A — Cryptographic anchoring",
  B: "Category B — Statistical bounds per metric",
  C: "Category C — Multi-metric correlations",
  D: "Category D — Temporal patterns",
  E: "Category E — Continuity",
  F: "Category F — Score and recommendation"
};

const STATUS_BADGE: Record<string, string> = {
  pass: "PASS",
  warn: "WARN",
  fail: "FAIL"
};

export function formatMarkdown(report: LegitimacyReport): string {
  const out: string[] = [];
  out.push(`# Amach Health — Legitimacy Report`);
  out.push("");
  out.push(`**Generated:** ${report.generatedAt}`);
  out.push(`**Wallet:** \`${report.walletAddress}\``);
  out.push(`**Network:** ${report.network ?? "(unspecified)"}`);
  out.push("");

  // Executive summary
  out.push("## Executive summary");
  out.push("");
  out.push(`- **Score:** ${report.score.toFixed(3)} (threshold ${report.threshold.toFixed(2)})`);
  out.push(
    `- **Recommendation:** ${
      report.recommendation === "pass" ? "PASS" : "FAIL"
    }`
  );
  out.push(`- **Leaves examined:** ${report.leafCount}`);
  out.push(
    `- **Day range:** ${report.dayRange.startDayId ?? "?"} – ${report.dayRange.endDayId ?? "?"}`
  );
  out.push(`- **Expected root:** \`${report.expectedRoot}\``);
  out.push(`- **Computed root:** \`${report.computedRoot ?? "(not computed)"}\``);
  out.push(`- **Failures:** ${report.failures.length}`);
  out.push(`- **Warnings:** ${report.warnings.length}`);
  out.push("");

  if (report.notes.length > 0) {
    out.push("### Notes");
    out.push("");
    for (const n of report.notes) out.push(`- ${n}`);
    out.push("");
  }

  // Categories
  for (const cat of report.categories) {
    out.push(`## ${CATEGORY_TITLES[cat.category]} — ${STATUS_BADGE[cat.status]}`);
    out.push("");
    out.push(renderCategoryTable(cat));
    out.push("");
  }

  // Findings
  if (report.failures.length > 0) {
    out.push(`## Failures (${report.failures.length})`);
    out.push("");
    for (const f of report.failures) out.push(`- ${f}`);
    out.push("");
  }
  if (report.warnings.length > 0) {
    out.push(`## Warnings (${report.warnings.length})`);
    out.push("");
    for (const w of report.warnings) out.push(`- ${w}`);
    out.push("");
  }
  if (report.failures.length === 0 && report.warnings.length === 0) {
    out.push("## Findings");
    out.push("");
    out.push("No findings. All checks passed.");
    out.push("");
  }

  out.push("---");
  out.push("");
  out.push(`Report generated by @amach/legitimacy v${report.version}`);
  out.push("");
  return out.join("\n");
}

function renderCategoryTable(category: CategoryResult): string {
  if (category.checks.length === 0) return "_(no checks ran in this category)_";
  const lines: string[] = [];
  lines.push("| ID | Status | Check | Value | Bound | Notes |");
  lines.push("|---|---|---|---|---|---|");
  for (const c of category.checks) {
    lines.push(renderRow(c));
  }
  return lines.join("\n");
}

function renderRow(c: CheckResult): string {
  const cells = [
    c.id,
    STATUS_BADGE[c.status],
    c.name,
    formatValue(c.value),
    c.bound ?? "—",
    truncate(c.message, 90)
  ];
  return `| ${cells.map(escapeCell).join(" | ")} |`;
}

function formatValue(v: number | string | null | undefined): string {
  if (v === null || v === undefined) return "—";
  return String(v);
}

function truncate(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1) + "…";
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
