#!/usr/bin/env node

/**
 * Email Setup Helper for Amach Health Admin Dashboard
 *
 * This script helps you set up email configuration for the admin dashboard.
 * Run with: node setup-email.js
 */

const fs = require("fs");
const path = require("path");

console.log("🚀 Amach Health Admin Dashboard - Email Setup Helper\n");

const envPath = path.join(__dirname, ".env.local");

// Check if .env.local already exists
if (fs.existsSync(envPath)) {
  console.log("⚠️  .env.local already exists. Backing up to .env.local.backup");
  fs.copyFileSync(envPath, path.join(__dirname, ".env.local.backup"));
}

// Create .env.local template
const envContent = `# Email Configuration for Admin Dashboard
# Generated by setup-email.js

# Gmail Configuration (Recommended)
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_SECURE=false
EMAIL_USER=your-email@gmail.com
EMAIL_PASS=your-16-character-app-password

# Verification URL (where users will be directed)
NEXT_PUBLIC_VERIFICATION_URL=http://localhost:3000/verify

# Admin Configuration
ADMIN_SECRET_KEY=your-super-secure-admin-key
NEXT_PUBLIC_ADMIN_ENABLED=true

# Instructions:
# 1. Enable 2-Factor Authentication on your Google account
# 2. Go to: https://myaccount.google.com/apppasswords
# 3. Generate an App Password for "Mail"
# 4. Use the 16-character password as EMAIL_PASS
# 5. NEVER use your regular Gmail password
`;

fs.writeFileSync(envPath, envContent);

console.log("✅ Created .env.local file");
console.log("\n📧 Next Steps:");
console.log("1. Open .env.local in your editor");
console.log('2. Replace "your-email@gmail.com" with your Gmail address');
console.log("3. Generate a Gmail App Password:");
console.log("   - Enable 2FA on your Google account");
console.log("   - Go to: https://myaccount.google.com/apppasswords");
console.log('   - Select "Mail" and generate a password');
console.log("   - Use the 16-character password as EMAIL_PASS");
console.log('4. Replace "your-super-secure-admin-key" with a secure key');
console.log("\n🔒 Security Notes:");
console.log("- NEVER commit .env.local to version control");
console.log("- Use App Passwords, not regular passwords");
console.log("- Keep your admin key secure");
console.log(
  "\n🎉 After setup, restart your admin app and test the email system!",
);
